language: python
python:
- 2.7
- 3.5
install:
- pip install nose
- pip install flake8
- pip install coveralls
script:
- flake8 gatilegrid tests
- coverage run --source=gatilegrid setup.py test
after_success: coveralls
